### ISSUE TITLE
Compatibility Php 7.0 Dan Php 7.1.x

### ISSUE THREAD

**Issue by Jawanet** [veritrans/SNAP-whmcs#1]
Mohon cek dan perbarui kompatibilitas php dengan php 7.0 terutama php 7.1.x up.

**Comment by rizdaprasetya** [comment]
Terima kasih feedbacknya, akan dicek untuk compatibility dengan PHP 7 & 7.1
Sudah pernah dicoba di PHP 7 Mas? boleh info ada error log apa saja yang didapat? Untuk membantu fix compatibility issue.

**Comment by Jawanet** [comment]
Sudah lupa saya logs error nya mas, nanti jika sudah menggunakan midtrans lagi saya infokan.

**Comment by rizdaprasetya** [comment]
Confirmed sudah bisa works di PHP v7.2 & WHMCS v7.6.x
