### ISSUE TITLE
GoPay Payment Instruction: undefined URL

### ISSUE THREAD

**Issue by AbuGosok** [veritrans/SNAP-whmcs#11]
Mohon maaf kalau saya salah tempat, atau isu ini memang berasal dari API midtrans. Kalau salah boleh ditutup / dipindahkan :)

**Percobaan 1:**
- Buka halaman invoice
- Popup halaman pembayaran midtrans muncul
- Pilih transfer bank
- Pilih banknya, disini saya coba Bank Permata
- Tutup halaman pembayaran midtrans
Setelah ini, status invoice akan menjadi "Awaiting Payment" seperti di gambar berikut (lihat hyperlink di pojok kiri bawah saat mouse hover ke tombol " View Payment Instruction") :
![payment-instruction](https://user-images.githubusercontent.com/7362316/70174081-32a76180-170f-11ea-98e1-4f8b717c9dba.jpg)

Saat kita klik tombol Payment Instruction, maka akan muncul instruksi berikut (pada kasus saya, saya pilih Bank Permata
![payment-instruction2](https://user-images.githubusercontent.com/7362316/70174246-7b5f1a80-170f-11ea-9e2d-69caeb19a57a.jpg)

Hal diatas sudah benar.

**Percobaan 2:**
Namun masalah terjadi jika saya memilih metode penggunaan GoPay hingga muncul QR code, kemudian menutupnya dan kembali ke halaman invoice. Link tombol "Payment Instruction" malah menjadi https://billing.hostingsaya.com/undefined

Sepertinya link instruksi pembayaran dengan GoPay belum diimplementasi ataukah ada hal lain? Karena siapa tahu si client ingin membuka Payment Instructionnya lagi untuk melihat GoPay QR Code yang dia tidak sengaja tutup.

Ataukah client harus menunggu 15 menit hingga timeout?

Terima kasih banyak atas module ini @rizdaprasetya

**Comment by rizdaprasetya** [comment]
Hi @AbuGosok secara product Snap memang tidak me-return PDF instruction url untuk payment GoPay. Karena bersifat payment yg cepat dan customer cukup mengerti, limit defaultnya 15 menit, PDF url tidak/belum diimplementasi, kami juga sudah request ke team Snap, tapi kelihatannya belum priority.

Ketika module WHMCS didevelop belum ada case GoPay jadi belum di handle. Untuk sekarang handling yg diimplementasikan jika PDF URL tidak ada, link tidak akan ditampilkan, untuk mencegah redirect ke `undefined`.
https://github.com/veritrans/SNAP-whmcs/commit/9654b2708c68ba3200bbba78f331ac6c58593d03

**Comment by AbuGosok** [comment]
Fixnya makes sense. Nanti kalau team SNAP sudah ada PFD untuk gopay, link PDF akan otomatis ada.

Terima kasih @rizdaprasetya issue ini bisa di close :)
