### ISSUE TITLE
 Exception: Veritrans Error (404): The requested resource is not found in 

### ISSUE THREAD

**Issue by adamramadhan** [veritrans/SNAP-whmcs#2]
Exception: Veritrans Error (404): The requested resource is not found in /home//public_html/modules/gateways/veritrans-lib/Veritrans/ApiRequestor.php:96
Stack trace:

**Comment by adamramadhan** [comment]
menggunakan latest semuanya per hari ini

**Comment by rizdaprasetya** [comment]
Halo @adamramadhan 
404 dikarenakan transaksi tersebut tidak ada di akun Midtrans Anda. SIlahkan lakukan transaksi terlebih dahulu.

Ketika sedang dalam tahap apa error ini muncul? testing notification dari Dashboard kah?
Test notification merupakan dummy transaction, jadi akan menghasilkan 404, karena transaksi tidak ada di akun Midtrans Anda. Silahkan tes notifikasi dengan membuat transaksi sandbox langsung, setelah payment complete, notification akan otomatis dikirim dan mengubah status transaksi dengan benar.

Thanks

**Comment by fixxay** [comment]
Cara panggil notificationya gmna ya? Apakah dibuat di controlles tersendiri atau dibuat metode aja?

**Comment by rizdaprasetya** [comment]
Hi @fixxay ini adalah repository untuk plugin payment WHMCS. Apakah pertanyaan terkait plugin ini atau Midtrans secara general? Bisa diperjelas pertanyaannya?

Jika pertanyaan general, untuk respon pertanyaan lebih jelas bisa melalui email support[at]midtrans.com

**Comment by fixxay** [comment]
Terkait repository github.

Pada tanggal Jum, 20 Sep 2019 14:18, Rizda Dwi Prasetya <
notifications@github.com> menulis:
